BEGIN;
SELECT plan(48);
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at) VALUES
  ('00000000-0000-0000-0000-000000000000', '61111111-1111-4111-8111-111111111111', 'authenticated', 'authenticated', 'conversation-admin@example.test', '', now()),
  ('00000000-0000-0000-0000-000000000000', '62222222-2222-4222-8222-222222222222', 'authenticated', 'authenticated', 'conversation-operator@example.test', '', now()),
  ('00000000-0000-0000-0000-000000000000', '63333333-3333-4333-8333-333333333333', 'authenticated', 'authenticated', 'conversation-inactive@example.test', '', now());
UPDATE public.usuarios SET role = 'admin' WHERE id IN ('61111111-1111-4111-8111-111111111111', '63333333-3333-4333-8333-333333333333');
UPDATE public.usuarios SET active = false WHERE id = '63333333-3333-4333-8333-333333333333';

SELECT has_table('public', 'whatsapp_conversation_state', 'state table exists');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid = 'public.whatsapp_conversation_state'::regclass), 'RLS enabled');
SELECT ok(NOT has_table_privilege('anon', 'public.whatsapp_conversation_state', 'SELECT'), 'anon cannot read');
SELECT ok(NOT has_table_privilege('authenticated', 'public.whatsapp_conversation_state', 'UPDATE'), 'admin cannot directly write');
SELECT ok(NOT has_table_privilege('service_role', 'public.whatsapp_conversation_state', 'UPDATE'), 'service role must use CAS');
SELECT ok(NOT has_function_privilege('anon', 'public.set_conversation_state(text,integer,jsonb,timestamptz)', 'EXECUTE'), 'anon cannot CAS');
SELECT ok(NOT has_function_privilege('authenticated', 'public.set_conversation_state(text,integer,jsonb,timestamptz)', 'EXECUTE'), 'authenticated cannot CAS');
SELECT ok(NOT has_function_privilege('service_role', 'public.take_over_conversation(text)', 'EXECUTE'), 'service role cannot take control');
SELECT ok(NOT has_function_privilege('anon', 'public.hand_back_conversation(text)', 'EXECUTE'), 'anon cannot hand back');
SELECT ok((SELECT bool_and(proconfig @> ARRAY['search_path=""']) FROM pg_proc WHERE proname IN ('set_conversation_state','take_over_conversation','hand_back_conversation')), 'RPCs have empty search_path');

SET LOCAL ROLE service_role;
SELECT is(public.set_conversation_state('50760000001', NULL, '{"flowVersion":1,"nodeId":"menu","variables":{},"awaiting":null,"owner":"bot"}', now()+interval '1 day'), true, 'creates state');
SELECT is(public.set_conversation_state('50760000001', NULL, '{"flowVersion":1,"nodeId":"menu","variables":{},"awaiting":null,"owner":"bot"}', now()+interval '1 day'), false, 'conflicting create rejected');
SELECT is(public.set_conversation_state('50760000001', 1, '{"flowVersion":1,"nodeId":"menu","variables":{"interes":"peliculas"},"awaiting":null,"owner":"bot"}', now()+interval '1 day'), true, 'CAS updates atomically');
SELECT is(public.set_conversation_state('50760000001', 1, '{"flowVersion":1,"nodeId":"menu","variables":{},"awaiting":null,"owner":"bot"}', now()+interval '1 day'), false, 'stale CAS rejected');
SELECT throws_ok($$SELECT public.set_conversation_state('invalid',NULL,'{}',now()+interval '1 day')$$, '22023', 'invalid conversation state', 'invalid identity rejected');
SELECT throws_ok($$SELECT public.set_conversation_state('50760000002',NULL,'{"flowVersion":1,"nodeId":"menu","variables":{"password":"synthetic"},"awaiting":null,"owner":"bot"}',now()+interval '1 day')$$, '22023', 'invalid conversation state', 'sensitive variable rejected');
SELECT throws_ok($$SELECT public.set_conversation_state('50760000002',NULL,'{"flowVersion":1,"nodeId":"menu","variables":[],"awaiting":null,"owner":"bot"}',now()+interval '1 day')$$, '22023', 'invalid conversation state', 'variables must be object');
SELECT throws_ok($$SELECT public.set_conversation_state('50760000002',NULL,jsonb_build_object('flowVersion',1,'nodeId','menu','variables',jsonb_build_object('note',repeat('x',5000)),'awaiting',NULL,'owner','bot'),now()+interval '1 day')$$, '22023', 'invalid conversation state', 'oversized variables rejected');
SELECT throws_ok($$SELECT public.set_conversation_state('50760000002',NULL,'{"flowVersion":1,"nodeId":"menu","variables":{},"awaiting":null,"owner":"otro"}',now()+interval '1 day')$$, '22023', 'invalid conversation state', 'invalid ownership rejected');
SELECT throws_ok($$SELECT public.set_conversation_state('50760000002',NULL,'{"flowVersion":1,"nodeId":"menu","variables":{},"awaiting":{"tipo":"text","ref":"menu","expiresAt":"infinity"},"owner":"bot"}',now()+interval '1 day')$$, '22023', 'invalid conversation state', 'invalid awaiting rejected');
SELECT throws_ok($$SELECT public.set_conversation_state('50760000002',NULL,'{"flowVersion":1,"nodeId":"menu","variables":{},"awaiting":null,"owner":"bot"}',now()-interval '1 day')$$, '22023', 'invalid conversation state', 'expired state write rejected');
SELECT throws_ok($$SELECT public.set_conversation_state('50760000001',2,jsonb_build_object('flowVersion',1,'nodeId','menu','variables','{}'::jsonb,'awaiting',jsonb_build_object('tipo','text','ref','other','expiresAt',now()+interval '5 minutes'),'owner','bot'),now()+interval '1 day')$$, '23514', NULL, 'awaiting must reference current node');
SELECT throws_ok($$SELECT public.set_conversation_state('50760000001',2,'{"flowVersion":1,"nodeId":"menu","variables":{},"awaiting":[],"owner":"bot"}',now()+interval '1 day')$$, '22023', 'invalid conversation state', 'awaiting must be object');
SELECT throws_ok($$SELECT public.set_conversation_state('50760000001',2,'{"flowVersion":999999999,"nodeId":"menu","variables":{},"awaiting":null,"owner":"bot"}',now()+interval '1 day')$$, '23503', NULL, 'flow version must exist');
SELECT is((SELECT revision FROM public.whatsapp_conversation_state WHERE wa_id='50760000001'),2,'failed mutations roll back atomically');
SELECT is(public.set_conversation_state('50760000001',2,jsonb_build_object('flowVersion',1,'nodeId','menu','variables','{"interes":"peliculas"}'::jsonb,'awaiting',jsonb_build_object('tipo','text','ref','menu','expiresAt',now()+interval '5 minutes'),'owner','bot'),now()+interval '1 day'),true,'stores valid awaiting');
SELECT ok((SELECT awaiting IS NOT NULL FROM public.whatsapp_conversation_state WHERE wa_id='50760000001'),'awaiting exists before takeover');
RESET ROLE;

SELECT set_config('request.jwt.claims','{"sub":"62222222-2222-4222-8222-222222222222","role":"authenticated"}',true);
SET LOCAL ROLE authenticated;
SELECT is((SELECT count(*) FROM public.whatsapp_conversation_state),0::bigint,'operator cannot read');
SELECT throws_ok($$SELECT public.take_over_conversation('50760000001')$$,'42501','forbidden','operator cannot take over');
SELECT throws_ok($$SELECT public.hand_back_conversation('50760000001')$$,'42501','forbidden','operator cannot hand back');
RESET ROLE;
SELECT set_config('request.jwt.claims','{"sub":"63333333-3333-4333-8333-333333333333","role":"authenticated"}',true);
SET LOCAL ROLE authenticated;
SELECT throws_ok($$SELECT public.take_over_conversation('50760000001')$$,'42501','forbidden','inactive admin denied');
RESET ROLE;
SELECT set_config('request.jwt.claims','{"sub":"61111111-1111-4111-8111-111111111111","role":"authenticated"}',true);
SET LOCAL ROLE authenticated;
SELECT is((SELECT count(*) FROM public.whatsapp_conversation_state),1::bigint,'admin reads');
SELECT is(public.take_over_conversation('50760000001'),true,'admin takes control');
SELECT is((SELECT owner FROM public.whatsapp_conversation_state WHERE wa_id='50760000001'),'humano','human ownership persisted');
SELECT is((SELECT revision FROM public.whatsapp_conversation_state WHERE wa_id='50760000001'),4,'takeover increments revision');
SELECT throws_ok($$SELECT public.take_over_conversation('invalid')$$,'22023','invalid conversation id','admin identity validated');
SELECT is(public.take_over_conversation('50760000999'),false,'missing chat not created implicitly');
RESET ROLE;
SET LOCAL ROLE service_role;
SELECT is(public.set_conversation_state('50760000001',4,'{"flowVersion":1,"nodeId":"menu","variables":{},"awaiting":null,"owner":"bot"}',now()+interval '1 day'),false,'bot cannot overwrite human even with current revision');
RESET ROLE;
SET LOCAL ROLE authenticated;
SELECT is(public.hand_back_conversation('50760000001'),true,'admin hands back');
SELECT is((SELECT owner FROM public.whatsapp_conversation_state WHERE wa_id='50760000001'),'bot','bot ownership restored');
SELECT is((SELECT revision FROM public.whatsapp_conversation_state WHERE wa_id='50760000001'),5,'handback increments revision');
SELECT ok((SELECT awaiting IS NULL FROM public.whatsapp_conversation_state WHERE wa_id='50760000001'),'awaiting cleared');
SELECT is((SELECT variables->>'interes' FROM public.whatsapp_conversation_state WHERE wa_id='50760000001'),'peliculas','takeover and handback preserve answers');
RESET ROLE;
SET LOCAL ROLE service_role;
SELECT is(public.set_conversation_state('50760000001',2,'{"flowVersion":1,"nodeId":"menu","variables":{},"awaiting":null,"owner":"bot"}',now()+interval '1 day'),false,'ABA stale revision rejected after handback');
SELECT is(public.set_conversation_state('50760000001',5,'{"flowVersion":1,"nodeId":"menu","variables":{},"awaiting":null,"owner":"humano"}',now()+interval '1 day'),true,'bot can persist fixed handoff');
SELECT is(public.set_conversation_state('50760000001',6,'{"flowVersion":1,"nodeId":"menu","variables":{},"awaiting":null,"owner":"bot"}',now()+interval '1 day'),false,'bot cannot hand back its own human handoff');
RESET ROLE;
SET LOCAL ROLE anon;
SELECT throws_ok($$SELECT * FROM public.whatsapp_conversation_state$$,'42501',NULL,'anon denied by grants');
RESET ROLE;
SELECT is((public.run_security_audit_validations()->>'unapproved_security_definer_executable_by_authenticated')::integer,0,'admin RPCs approved by canonical audit');
SELECT * FROM finish();
ROLLBACK;
